[".local/share/zinit/zinit.git"]
  type = "git-repo"
  url = "https://github.com/zdharma-continuum/zinit.git"

[".cache/dein/repos/github.com/Shougo/dein.vim"]
  type = "git-repo"
  url = "https://github.com/Shougo/dein.vim.git"
