---
name: "Setup Chezmoi Environment"
description: "Common setup steps for chezmoi workflows"

inputs:
  msys2-packages:
    description: "Additional MSYS2 packages to install (space-separated)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install MSYS2 packages (Windows)
      run: |
        C:/msys64/usr/bin/pacman.exe -Sy --noconfirm git unzip ${{ inputs.msys2-packages }}
      shell: C:\msys64\usr\bin\bash.exe --noprofile --norc -eo pipefail {0}
      if: runner.os == 'Windows'

    - name: Install chezmoi (Windows)
      run: |
        mkdir -p ${HOME}/.local/bin
        sh -c "$(curl -fsLS get.chezmoi.io)" -b ${HOME}/.local/bin
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
      shell: C:\msys64\usr\bin\bash.exe --noprofile --norc -eo pipefail {0}
      if: runner.os == 'Windows'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Run install.sh
      run: ./install.sh
      shell: ${{ runner.os == 'Windows' && 'C:\msys64\usr\bin\bash.exe --noprofile --norc -eo pipefail {0}' || 'bash' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Setup aqua (Linux/macOS)
      run: |
        echo "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin" >> "${GITHUB_PATH}"
        echo "AQUA_GLOBAL_CONFIG=${HOME}/.config/aquaproj-aqua/aqua.yaml" >> "${GITHUB_ENV}"
      shell: "bash"
      if: runner.os != 'Windows'

    - name: Setup aqua (Windows)
      run: |
        echo "${HOME}/AppData/Local/aquaproj-aqua/bin" >> "${GITHUB_PATH}"
        echo "AQUA_GLOBAL_CONFIG=${HOME}/.config/aquaproj-aqua/aqua.yaml" >> "${GITHUB_ENV}"
      shell: C:\msys64\usr\bin\bash.exe --noprofile --norc -eo pipefail {0}
      if: runner.os == 'Windows'
