---
name: "Setup Chezmoi Environment"
description: "Common setup steps for chezmoi workflows"

inputs:
  msys2-packages:
    description: "Additional MSYS2 packages to install (space-separated)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup MSYS2 (Windows)
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          unzip
          ${{ inputs.msys2-packages }}
        path-type: inherit
      if: runner.os == 'Windows'

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Run install.sh
      run: ./install.sh
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Setup mise environment
      run: |
        echo "${LOCALAPPDATA}\\Microsoft\\WinGet\\Links" >> "${GITHUB_PATH}"
        echo "${HOME}/.local/share/mise/shims" >> "${GITHUB_PATH}"
      shell: ${{ runner.os == 'Windows' && 'msys2 {0}' || 'bash' }}
