---
name: "Setup Chezmoi Environment"
description: "Common setup steps for chezmoi workflows"

runs:
  using: "composite"
  steps:
    - name: Setup Path for WinGet (Windows)
      run: |
        echo "${LOCALAPPDATA}\\Microsoft\\WinGet\\Links" >> "${GITHUB_PATH}"
      shell: bash
      if: runner.os == 'Windows'

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*

    - name: Run install.sh
      run: ./install.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Setup mise environment (Unix)
      run: |
        echo "${HOME}/.local/bin" >> "${GITHUB_PATH}"
        echo "${HOME}/.local/share/mise/shims" >> "${GITHUB_PATH}"
      shell: bash
      if: runner.os != 'Windows'

    - name: Setup mise environment (Windows)
      run: |
        echo "${LOCALAPPDATA}\\mise\\shims" >> "${GITHUB_PATH}"
      shell: bash
      if: runner.os == 'Windows'
