---
name: Lint files

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Run shellcheck
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          shellcheck_flags: --external-sources --exclude=SC1090
          pattern: |
            *.sh
            .profile
            .bashrc
            .bash_profile
  lint-vint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Run vint
        uses: reviewdog/action-vint@b249164f0c17d7a24aecccea84f2c7e132072731 # v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
  lint-actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Run actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
  lint-tomlcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Install tomlcheck
        run: |
          curl -L https://github.com/vmchale/tomlcheck/releases/download/0.1.0.38/tomlcheck-x86_64-unkown-linux-gnu -o /usr/local/bin/tomlcheck
          chmod 755 /usr/local/bin/tomlcheck
      - name: Run tomlcheck
        run: find . -type f -name '*.toml' -printf '%P\n' | xargs -t -I{} -n1 sh -c 'tomlcheck -f {} || echo "::error file={}::Toml lint check failed"'
